### ISSUE TITLE
GlucoseUnit is not detected properly

### ISSUE THREAD

**Issue by nielsmaerten** [nielsmaerten/gluco-check#130]
**Describe the bug**
Reported via Reddit: https://www.reddit.com/r/diabetes/comments/nlt6xj/hey_google_check_my_sugar/gzo60si/?utm_source=reddit&utm_medium=web2x&context=3  
I went to check the db, and it turns out there are several users with their Nightscout set to _mg/dl_, but we have their unit set to _mmol/L_.

Looks like detection of the glucoseUnit isn't working.  
Not sure yet if this is a backend/frontend bug, but I'll enable glucoseUnitField on prod as a temporary fix.

**To Reproduce**
TBD

**Expected behavior**
When signing up with a Nightscout site using mg/dl, the settings in Gluco Check should copy that value

**Additional context**
Adding a hotfix to deal with this by always showing glucoseUnitField, even on prod.

**Comment by nielsmaerten** [comment]
@ddamico Do you have time to look into this?

I plugged a few nightscout urls into the validator and it seems to be detecting the unit correctly. So I don't think it's a backend issue.

I _think_ (working theory) what happens is that users paste in their url and token, and click save **before** a validation has been able to complete.
Because mmol/L is the default glucoseUnit, and because you can click save even before the info has been validated,
the default (mmol/L) gets saved to Firestore, instead of mg/dl. Feels like some kind of race condition.

Are you able to verify this? If I'm correct, the proper way of fixing this would probably be implementing #122, because that will change the behavior to validate after a user clicks save.

As a temporary fix, I turned the glucoseUnitField back on in production. That way users will have a way to set the units themselves.

**Comment by nielsmaerten** [comment]
Update: #132 is a script to automatically fix this bug for users who were already affected.  
It's a simple script that checks the Nightscout Unit for every user, and updates it in our own DB should there be a mismatch.

Now we no longer have to consider this a major issue. There's a script to fix existing accounts, plus reactivating glucoseUnitField allows users to set the value for themselves.

**Comment by ddamico** [comment]
@nielsmaerten Thanks so much for taking care of re-enabling the field and putting together the script. From what I've been able to see so far, your theory of what's happening is correct, we're saving the default before we've had a chance to fetch a real value. Agree that with the field re-enabled and the script to repair this becomes less critical, but will do my best to get moving on the reworking of the form.
