### ISSUE TITLE
Pump battery level not available for Loop-accounts

### ISSUE THREAD

**Issue by nielsmaerten** [nielsmaerten/gluco-check#20]
- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

- **What is the current behavior?**
Loop does not upload the pump's battery level to Nightscout, so the user can't ask for it.

- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem:**
Say: "Ask Gluco Check for everything" or "Ask Gluco Check for the battery level"  
Assistant says: "Pump's battery level is at <silence> percent" - There's no value, so the placeholder is just empty.  

- **What is the expected behavior?**  
TBD.

- **Please tell us about your environment:**
Use a Loop-account (= an account connected to a Nightscout site that's using Loop, not OpenAPS)

**Comment by nielsmaerten** [comment]
IMHO...  

- when asking for all values (Hey Google, ask Gluco Check for everything), the battery level one should just be skipped. In fact, all values that aren't available should not be mentioned at all.

- In the second case, asking for a value explicitly (Hey Google, ask Gluco Check for my battery level), the Assistant should answer that this value is unavailable.

**Comment by ddamico** [comment]
> * when asking for all values (Hey Google, ask Gluco Check for everything), the battery level one should just be skipped. In fact, all values that aren't available should not be mentioned at all.
> * In the second case, asking for a value explicitly (Hey Google, ask Gluco Check for my battery level), the Assistant should answer that this value is unavailable.

As the loop user on the thread would just like to say, 100% agree with your take on this, skip when in combination with other values and report as unavailable when specifically asked for.

**Comment by nielsmaerten** [comment]
PR #22 resolves this issue as discussed above.
